version: "2"

linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
