/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects with their last analysis and export */
        get: operations["listProjects"];
        put?: never;
        /** Create a project from an uploaded package.json and start an analysis */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get a project, its target and its history */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete the project directory */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/target": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Change the project's target platform and toolchain */
        put: operations["setProjectTarget"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue an analysis for the project */
        post: operations["queueAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/analyses/{analysisId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        /** Get an analysis' status and results */
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        /** Delete an analysis */
        delete: operations["deleteAnalysis"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/analyses/{analysisId}/log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        /** Get an analysis' full log */
        get: operations["getAnalysisLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/analyses/{analysisId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running or queued analysis */
        post: operations["cancelAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/analyses/{analysisId}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue an export with a version selection */
        post: operations["queueExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        /** Get an export's status and files */
        get: operations["getExport"];
        put?: never;
        post?: never;
        /** Delete an export */
        delete: operations["deleteExport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/exports/{exportId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running or queued export */
        post: operations["cancelExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/exports/{exportId}/files/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
                /** @description File name inside the export directory */
                name: string;
            };
            cookie?: never;
        };
        /** Download one file of a finished export */
        get: operations["downloadExportFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/current/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events of the running job
         * @description Streams the five event kinds of the job queue: step, progress, candidate, log, end. Replays the running job's events so far, then streams live ones. The stream ends after the end event.
         */
        get: operations["watchJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get settings, with signatureKey masked */
        get: operations["getSettings"];
        /** Update settings */
        put: operations["updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Installed and available tool versions, DB date */
        get: operations["getTools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/trivy/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install a new Trivy release */
        post: operations["updateTrivy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/trivy/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate an installed Trivy version */
        post: operations["activateTrivy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/trivy/db/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force a Trivy DB download */
        post: operations["updateTrivyDB"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details for HTTP APIs */
        Problem: {
            /**
             * Format: uri
             * @description A URI identifying the problem type
             * @default about:blank
             */
            type: string;
            /** @description A short, human-readable summary of the problem type */
            title: string;
            /** @description The HTTP status code repeated for clients that read the body only */
            status: number;
            /** @description A human-readable explanation specific to this occurrence */
            detail?: string;
            /**
             * Format: uri
             * @description A URI identifying this specific occurrence
             */
            instance?: string;
            /** @description Every offending entry, for a validation failure */
            errors?: components["schemas"]["ProblemDetail"][];
            /** @description Names of what a tools-missing problem needs and does not have yet */
            missing?: string[];
        };
        /** @description One offending entry inside a validation failure's errors list */
        ProblemDetail: {
            /** @description package.json field, such as dependencies or pnpm.overrides */
            field: string;
            /** @description Dependency name, empty for a field-level problem */
            name?: string;
            value?: string;
            reason: string;
        };
        /**
         * @description State of a job and of the directory it writes
         * @enum {string}
         */
        State: "queued" | "running" | "done" | "failed" | "cancelled" | "interrupted";
        /** @description The system a resolution or an export is prepared for */
        Target: {
            /** @example linux */
            os: string;
            /** @example x64 */
            cpu: string;
            /** @example glibc */
            libc: string;
            /** @example 22.17.1 */
            node: string;
            /** @example 10.34.5 */
            pnpmVer: string;
        };
        /** @description Every value the interface can change. */
        Settings: {
            target: components["schemas"]["Target"];
            /** @description Masked on read, never logged */
            signatureKey: string;
            minReleaseAgeDays: number;
            resolveParallelism: number;
            downloadParallelism: number;
        };
        /** @description One row of the projects list. */
        ProjectSummary: {
            id: string;
            name: string;
            target: components["schemas"]["Target"];
            lastAnalysis?: components["schemas"]["Analysis"];
            lastExport?: components["schemas"]["Export"];
        };
        /** @description A project, its target and its analysis and export history. */
        Project: {
            id: string;
            name: string;
            target: components["schemas"]["Target"];
            /** @description sha256 of the uploaded package.json bytes, lowercase hex */
            manifestSha256?: string;
            analyses?: components["schemas"]["Analysis"][];
            exports?: components["schemas"]["Export"][];
        };
        /** @description One analysis job and its state. */
        Analysis: {
            id: string;
            projectId: string;
            state: components["schemas"]["State"];
            /** Format: date-time */
            createdAt: string;
            result?: components["schemas"]["AnalysisResult"];
            /** @description Trivy version the analysis used, absent when it did not record one */
            trivyVersion?: string;
            /**
             * Format: date-time
             * @description Vulnerability database date the analysis used, absent when it did not record one
             */
            trivyDbDate?: string;
            /** @description pnpm version the analysis used, absent when it did not record one */
            pnpmVersion?: string;
            failure?: components["schemas"]["Failure"];
        };
        /** @description Which step failed and why */
        Failure: {
            step: string;
            message: string;
        };
        /** @description CVE counts by severity, critical to unknown */
        Vector: number[];
        /** @description One vulnerability behind a Vector count */
        Cve: {
            /** @example CVE-2024-29041 */
            id: string;
            /**
             * @description As Trivy prints it, upper case
             * @example HIGH
             */
            severity: string;
        };
        /** @description One reason a candidate is blocked or worth a second look */
        Signal: {
            name: string;
            evidence: string;
            blocking: boolean;
        };
        /** @description One newer version of a dependency, ranked against the current one */
        Candidate: {
            version: string;
            vector: components["schemas"]["Vector"];
            /** @description The vulnerabilities behind vector, sorted by severity then id */
            cves: components["schemas"]["Cve"][];
            signals: components["schemas"]["Signal"][];
            /** @description Whether this candidate was resolved and scanned before the rest */
            key: boolean;
            resolved: boolean;
            /**
             * Format: date-time
             * @description Empty when the registry has no publication time
             */
            published?: string;
        };
        /** @description One direct dependency's current CVEs and its ranked candidates */
        DependencyResult: {
            name: string;
            current: string;
            /** @description Empty when no candidate improves on the current version */
            best?: string;
            vector: components["schemas"]["Vector"];
            /** @description The vulnerabilities behind vector, sorted by severity then id */
            cves: components["schemas"]["Cve"][];
            candidates: components["schemas"]["Candidate"][];
        };
        /** @description What an analysis writes to candidates.json and ranking.json */
        AnalysisResult: {
            target: components["schemas"]["Target"];
            before: components["schemas"]["Vector"];
            /** @description Null when the combined check (step 9) never measured it */
            after?: components["schemas"]["Vector"] | null;
            dependencies: components["schemas"]["DependencyResult"][];
            warnings: string[];
        };
        /** @description A selection of versions per dependency, plus the project tree flag */
        ExportRequest: {
            /** @description Dependency name to the list of its versions to include. An empty or absent list selects nothing for that dependency. */
            selection: {
                [key: string]: string[];
            };
            /**
             * @description Add the current project tree to the export
             * @default false
             */
            includeProject: boolean;
        };
        /** @description One export job, its state and its files. */
        Export: {
            id: string;
            projectId: string;
            analysisId: string;
            state: components["schemas"]["State"];
            /** Format: date-time */
            createdAt: string;
            /** @description File names available under files/{name} once the export is done */
            files?: string[];
            failure?: components["schemas"]["Failure"];
        };
        /** @description Installed and available pnpm and Trivy versions, and the DB date. */
        ToolsState: {
            pnpmInstalled: string[];
            trivyActive: string;
            trivyInstalled: string[];
            trivyLatest: string;
            /** @description Duration since the latest Trivy release, as a Go duration string */
            trivyLatestAge: string;
            /** Format: date-time */
            trivyDbDate: string;
            /** @description Size in bytes of the latest Trivy release asset for this host, 0 when the latest release is itself unavailable */
            latestSizeBytes: number;
            /** @description Whether trivy, its database and a signature key are all in place */
            ready: boolean;
            /** @description Names of what ready needs and does not have yet */
            missing: string[];
        };
        /**
         * @description Discriminator for the data payload of an Event.
         * @enum {string}
         */
        EventKind: "step" | "progress" | "candidate" | "log" | "end";
        /** @description One server-sent event of the running job */
        Event: {
            kind: components["schemas"]["EventKind"];
            /** @description Job ID the event belongs to */
            job: string;
            /** @description Store id (the directory id) of the job the event belongs to, set once the queue has started it. Empty for an event about a job cancelled before it started. */
            storeId?: string;
            /** @description Payload matching the kind; see StepData, ProgressData, CandidateData, LogData, EndData */
            data: components["schemas"]["StepData"] | components["schemas"]["ProgressData"] | components["schemas"]["CandidateData"] | components["schemas"]["LogData"] | components["schemas"]["EndData"];
        };
        /** @description Payload of a step event */
        StepData: {
            name: string;
            state: components["schemas"]["State"];
            durationMs?: number;
            /** @description err.Error() when state is failed, absent otherwise */
            error?: string;
        };
        /** @description Payload of a progress event */
        ProgressData: {
            /** @description Name of the step this progress belongs to, matching a StepData "name" from the same run. A client keys progress by this field, not by how many step events it has seen so far: a subscriber that only replays the tail of a long run's history can still place this progress under the right step. */
            step: string;
            done: number;
            total: number;
            estimatedRemainingMs?: number;
            /** @description Tarballs served from the tarball cache instead of downloaded, a running count. Only an export sends this; an analysis never does. */
            cacheHits?: number;
        };
        /** @description Payload of a candidate event */
        CandidateData: {
            dependency: string;
            version: string;
            /** @description CVE counts by severity, critical to unknown */
            vector: number[];
            signals: string[];
        };
        /** @description Payload of a log event */
        LogData: {
            line: string;
        };
        /** @description Payload of the end event, always the last one of a job */
        EndData: {
            state: components["schemas"]["State"];
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        AnalysisId: string;
        ExportId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                /** @description Filter to the projects created from this exact manifest hash (sha256 of the uploaded bytes, lowercase hex), newest first */
                manifestSha256?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Project name; defaults to the manifest name field */
                    name?: string;
                    /**
                     * Format: binary
                     * @description package.json content
                     */
                    manifest: string;
                };
            };
        };
        responses: {
            /** @description Project created, analysis queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    setProjectTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Target"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    queueAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getAnalysisLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plain text log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analysis after the cancel request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    queueExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                analysisId: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Export queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export after the cancel request */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    downloadExportFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["ProjectId"];
                exportId: components["parameters"]["ExportId"];
                /** @description File name inside the export directory */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    watchJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Event"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Updated settings, with signatureKey masked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tools state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsState"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateTrivy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Install the latest release regardless of its age */
                    force: boolean;
                };
            };
        };
        responses: {
            /** @description Tools state after the update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsState"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    activateTrivy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: string;
                };
            };
        };
        responses: {
            /** @description Tools state after the activation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsState"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    updateTrivyDB: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tools state after the DB update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsState"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
