//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventKind.
const (
	EventKindCandidate EventKind = "candidate"
	EventKindEnd       EventKind = "end"
	EventKindLog       EventKind = "log"
	EventKindProgress  EventKind = "progress"
	EventKindStep      EventKind = "step"
)

// Valid indicates whether the value is a known member of the EventKind enum.
func (e EventKind) Valid() bool {
	switch e {
	case EventKindCandidate:
		return true
	case EventKindEnd:
		return true
	case EventKindLog:
		return true
	case EventKindProgress:
		return true
	case EventKindStep:
		return true
	default:
		return false
	}
}

// Defines values for State.
const (
	Cancelled   State = "cancelled"
	Done        State = "done"
	Failed      State = "failed"
	Interrupted State = "interrupted"
	Queued      State = "queued"
	Running     State = "running"
)

// Valid indicates whether the value is a known member of the State enum.
func (e State) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Done:
		return true
	case Failed:
		return true
	case Interrupted:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Analysis One analysis job and its state.
type Analysis struct {
	CreatedAt time.Time `json:"createdAt"`

	// Failure Which step failed and why
	Failure *Failure `json:"failure,omitempty"`
	Id      string   `json:"id"`

	// PnpmVersion pnpm version the analysis used, absent when it did not record one
	PnpmVersion *string `json:"pnpmVersion,omitempty"`
	ProjectId   string  `json:"projectId"`

	// Result What an analysis writes to candidates.json and ranking.json
	Result *AnalysisResult `json:"result,omitempty"`

	// State State of a job and of the directory it writes
	State State `json:"state"`

	// TrivyDbDate Vulnerability database date the analysis used, absent when it did not record one
	TrivyDbDate *time.Time `json:"trivyDbDate,omitempty"`

	// TrivyVersion Trivy version the analysis used, absent when it did not record one
	TrivyVersion *string `json:"trivyVersion,omitempty"`
}

// AnalysisResult What an analysis writes to candidates.json and ranking.json
type AnalysisResult struct {
	// After Null when the combined check (step 9) never measured it
	After *Vector `json:"after"`

	// Before CVE counts by severity, critical to unknown
	Before       Vector             `json:"before"`
	Dependencies []DependencyResult `json:"dependencies"`

	// Target The system a resolution or an export is prepared for
	Target   Target   `json:"target"`
	Warnings []string `json:"warnings"`
}

// Candidate One newer version of a dependency, ranked against the current one
type Candidate struct {
	// Cves The vulnerabilities behind vector, sorted by severity then id
	Cves []Cve `json:"cves"`

	// Key Whether this candidate was resolved and scanned before the rest
	Key bool `json:"key"`

	// Published Empty when the registry has no publication time
	Published *time.Time `json:"published,omitempty"`
	Resolved  bool       `json:"resolved"`
	Signals   []Signal   `json:"signals"`

	// Vector CVE counts by severity, critical to unknown
	Vector  Vector `json:"vector"`
	Version string `json:"version"`
}

// CandidateData Payload of a candidate event
type CandidateData struct {
	Dependency string   `json:"dependency"`
	Signals    []string `json:"signals"`

	// Vector CVE counts by severity, critical to unknown
	Vector  []int  `json:"vector"`
	Version string `json:"version"`
}

// Cve One vulnerability behind a Vector count
type Cve struct {
	Id string `json:"id"`

	// Severity As Trivy prints it, upper case
	Severity string `json:"severity"`
}

// DependencyResult One direct dependency's current CVEs and its ranked candidates
type DependencyResult struct {
	// Best Empty when no candidate improves on the current version
	Best       *string     `json:"best,omitempty"`
	Candidates []Candidate `json:"candidates"`
	Current    string      `json:"current"`

	// Cves The vulnerabilities behind vector, sorted by severity then id
	Cves []Cve  `json:"cves"`
	Name string `json:"name"`

	// Vector CVE counts by severity, critical to unknown
	Vector Vector `json:"vector"`
}

// EndData Payload of the end event, always the last one of a job
type EndData struct {
	// State State of a job and of the directory it writes
	State State `json:"state"`
}

// Event One server-sent event of the running job
type Event struct {
	// Data Payload matching the kind; see StepData, ProgressData, CandidateData, LogData, EndData
	Data Event_Data `json:"data"`

	// Job Job ID the event belongs to
	Job string `json:"job"`

	// Kind Discriminator for the data payload of an Event.
	Kind EventKind `json:"kind"`

	// StoreId Store id (the directory id) of the job the event belongs to, set once the queue has started it. Empty for an event about a job cancelled before it started.
	StoreId *string `json:"storeId,omitempty"`
}

// Event_Data Payload matching the kind; see StepData, ProgressData, CandidateData, LogData, EndData
type Event_Data struct {
	union json.RawMessage
}

// EventKind Discriminator for the data payload of an Event.
type EventKind string

// Export One export job, its state and its files.
type Export struct {
	AnalysisId string    `json:"analysisId"`
	CreatedAt  time.Time `json:"createdAt"`

	// Failure Which step failed and why
	Failure *Failure `json:"failure,omitempty"`

	// Files File names available under files/{name} once the export is done
	Files     *[]string `json:"files,omitempty"`
	Id        string    `json:"id"`
	ProjectId string    `json:"projectId"`

	// State State of a job and of the directory it writes
	State State `json:"state"`
}

// ExportRequest A selection of versions per dependency, plus the project tree flag
type ExportRequest struct {
	// IncludeProject Add the current project tree to the export
	IncludeProject *bool `json:"includeProject,omitempty"`

	// Selection Dependency name to the list of its versions to include. An empty or absent list selects nothing for that dependency.
	Selection map[string][]string `json:"selection"`
}

// Failure Which step failed and why
type Failure struct {
	Message string `json:"message"`
	Step    string `json:"step"`
}

// LogData Payload of a log event
type LogData struct {
	Line string `json:"line"`
}

// Problem RFC 9457 Problem Details for HTTP APIs
type Problem struct {
	// Detail A human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Errors Every offending entry, for a validation failure
	Errors *[]ProblemDetail `json:"errors,omitempty"`

	// Instance A URI identifying this specific occurrence
	Instance *string `json:"instance,omitempty"`

	// Missing Names of what a tools-missing problem needs and does not have yet
	Missing *[]string `json:"missing,omitempty"`

	// Status The HTTP status code repeated for clients that read the body only
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type
	Title string `json:"title"`

	// Type A URI identifying the problem type
	Type *string `json:"type,omitempty"`
}

// ProblemDetail One offending entry inside a validation failure's errors list
type ProblemDetail struct {
	// Field package.json field, such as dependencies or pnpm.overrides
	Field string `json:"field"`

	// Name Dependency name, empty for a field-level problem
	Name   *string `json:"name,omitempty"`
	Reason string  `json:"reason"`
	Value  *string `json:"value,omitempty"`
}

// ProgressData Payload of a progress event
type ProgressData struct {
	// CacheHits Tarballs served from the tarball cache instead of downloaded, a running count. Only an export sends this; an analysis never does.
	CacheHits            *int `json:"cacheHits,omitempty"`
	Done                 int  `json:"done"`
	EstimatedRemainingMs *int `json:"estimatedRemainingMs,omitempty"`

	// Step Name of the step this progress belongs to, matching a StepData "name" from the same run. A client keys progress by this field, not by how many step events it has seen so far: a subscriber that only replays the tail of a long run's history can still place this progress under the right step.
	Step  string `json:"step"`
	Total int    `json:"total"`
}

// Project A project, its target and its analysis and export history.
type Project struct {
	Analyses *[]Analysis `json:"analyses,omitempty"`
	Exports  *[]Export   `json:"exports,omitempty"`
	Id       string      `json:"id"`

	// ManifestSha256 sha256 of the uploaded package.json bytes, lowercase hex
	ManifestSha256 *string `json:"manifestSha256,omitempty"`
	Name           string  `json:"name"`

	// Target The system a resolution or an export is prepared for
	Target Target `json:"target"`
}

// ProjectSummary One row of the projects list.
type ProjectSummary struct {
	Id string `json:"id"`

	// LastAnalysis One analysis job and its state.
	LastAnalysis *Analysis `json:"lastAnalysis,omitempty"`

	// LastExport One export job, its state and its files.
	LastExport *Export `json:"lastExport,omitempty"`
	Name       string  `json:"name"`

	// Target The system a resolution or an export is prepared for
	Target Target `json:"target"`
}

// Settings Every value the interface can change.
type Settings struct {
	DownloadParallelism int `json:"downloadParallelism"`
	MinReleaseAgeDays   int `json:"minReleaseAgeDays"`
	ResolveParallelism  int `json:"resolveParallelism"`

	// SignatureKey Masked on read, never logged
	SignatureKey string `json:"signatureKey"`

	// Target The system a resolution or an export is prepared for
	Target Target `json:"target"`
}

// Signal One reason a candidate is blocked or worth a second look
type Signal struct {
	Blocking bool   `json:"blocking"`
	Evidence string `json:"evidence"`
	Name     string `json:"name"`
}

// State State of a job and of the directory it writes
type State string

// StepData Payload of a step event
type StepData struct {
	DurationMs *int `json:"durationMs,omitempty"`

	// Error err.Error() when state is failed, absent otherwise
	Error *string `json:"error,omitempty"`
	Name  string  `json:"name"`

	// State State of a job and of the directory it writes
	State State `json:"state"`
}

// Target The system a resolution or an export is prepared for
type Target struct {
	Cpu     string `json:"cpu"`
	Libc    string `json:"libc"`
	Node    string `json:"node"`
	Os      string `json:"os"`
	PnpmVer string `json:"pnpmVer"`
}

// ToolsState Installed and available pnpm and Trivy versions, and the DB date.
type ToolsState struct {
	// LatestSizeBytes Size in bytes of the latest Trivy release asset for this host, 0 when the latest release is itself unavailable
	LatestSizeBytes int `json:"latestSizeBytes"`

	// Missing Names of what ready needs and does not have yet
	Missing       []string `json:"missing"`
	PnpmInstalled []string `json:"pnpmInstalled"`

	// Ready Whether trivy, its database and a signature key are all in place
	Ready          bool      `json:"ready"`
	TrivyActive    string    `json:"trivyActive"`
	TrivyDbDate    time.Time `json:"trivyDbDate"`
	TrivyInstalled []string  `json:"trivyInstalled"`
	TrivyLatest    string    `json:"trivyLatest"`

	// TrivyLatestAge Duration since the latest Trivy release, as a Go duration string
	TrivyLatestAge string `json:"trivyLatestAge"`

	// TrivyRecommended Newest Trivy release old enough to install without force, set only while the latest release is younger than the minimum release age
	TrivyRecommended *string `json:"trivyRecommended,omitempty"`
}

// Vector CVE counts by severity, critical to unknown
type Vector = []int

// AnalysisId defines model for AnalysisId.
type AnalysisId = string

// ExportId defines model for ExportId.
type ExportId = string

// ProjectId defines model for ProjectId.
type ProjectId = string

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// ManifestSha256 Filter to the projects created from this exact manifest hash (sha256 of the uploaded bytes, lowercase hex), newest first
	ManifestSha256 *string `form:"manifestSha256,omitempty" json:"manifestSha256,omitempty"`
}

// CreateProjectMultipartBody defines parameters for CreateProject.
type CreateProjectMultipartBody struct {
	// Manifest package.json content
	Manifest openapi_types.File `json:"manifest"`

	// Name Project name; defaults to the manifest name field
	Name *string `json:"name,omitempty"`
}

// ActivateTrivyJSONBody defines parameters for ActivateTrivy.
type ActivateTrivyJSONBody struct {
	Version string `json:"version"`
}

// UpdateTrivyJSONBody defines parameters for UpdateTrivy.
type UpdateTrivyJSONBody struct {
	// Force Install the latest release regardless of its age
	Force bool `json:"force"`

	// Version Install this release instead of the latest, such as the ToolsState.trivyRecommended version. Still subject to the minimum age check unless force is set.
	Version *string `json:"version,omitempty"`
}

// CreateProjectMultipartRequestBody defines body for CreateProject for multipart/form-data ContentType.
type CreateProjectMultipartRequestBody CreateProjectMultipartBody

// QueueExportJSONRequestBody defines body for QueueExport for application/json ContentType.
type QueueExportJSONRequestBody = ExportRequest

// SetProjectTargetJSONRequestBody defines body for SetProjectTarget for application/json ContentType.
type SetProjectTargetJSONRequestBody = Target

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = Settings

// ActivateTrivyJSONRequestBody defines body for ActivateTrivy for application/json ContentType.
type ActivateTrivyJSONRequestBody ActivateTrivyJSONBody

// UpdateTrivyJSONRequestBody defines body for UpdateTrivy for application/json ContentType.
type UpdateTrivyJSONRequestBody UpdateTrivyJSONBody

// AsStepData returns the union data inside the Event_Data as a StepData
func (t Event_Data) AsStepData() (StepData, error) {
	var body StepData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStepData overwrites any union data inside the Event_Data as the provided StepData
func (t *Event_Data) FromStepData(v StepData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStepData performs a merge with any union data inside the Event_Data, using the provided StepData
func (t *Event_Data) MergeStepData(v StepData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProgressData returns the union data inside the Event_Data as a ProgressData
func (t Event_Data) AsProgressData() (ProgressData, error) {
	var body ProgressData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProgressData overwrites any union data inside the Event_Data as the provided ProgressData
func (t *Event_Data) FromProgressData(v ProgressData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProgressData performs a merge with any union data inside the Event_Data, using the provided ProgressData
func (t *Event_Data) MergeProgressData(v ProgressData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCandidateData returns the union data inside the Event_Data as a CandidateData
func (t Event_Data) AsCandidateData() (CandidateData, error) {
	var body CandidateData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCandidateData overwrites any union data inside the Event_Data as the provided CandidateData
func (t *Event_Data) FromCandidateData(v CandidateData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCandidateData performs a merge with any union data inside the Event_Data, using the provided CandidateData
func (t *Event_Data) MergeCandidateData(v CandidateData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLogData returns the union data inside the Event_Data as a LogData
func (t Event_Data) AsLogData() (LogData, error) {
	var body LogData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLogData overwrites any union data inside the Event_Data as the provided LogData
func (t *Event_Data) FromLogData(v LogData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLogData performs a merge with any union data inside the Event_Data, using the provided LogData
func (t *Event_Data) MergeLogData(v LogData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEndData returns the union data inside the Event_Data as a EndData
func (t Event_Data) AsEndData() (EndData, error) {
	var body EndData
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEndData overwrites any union data inside the Event_Data as the provided EndData
func (t *Event_Data) FromEndData(v EndData) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEndData performs a merge with any union data inside the Event_Data, using the provided EndData
func (t *Event_Data) MergeEndData(v EndData) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// WatchJob Server-sent events of the running job
	// (GET /jobs/current/events)
	WatchJob(w http.ResponseWriter, r *http.Request)
	// ListProjects List projects with their last analysis and export
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams)
	// CreateProject Create a project from an uploaded package.json and start an analysis
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// DeleteProject Delete the project directory
	// (DELETE /projects/{projectId})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectId)
	// GetProject Get a project, its target and its history
	// (GET /projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectId)
	// QueueAnalysis Queue an analysis for the project
	// (POST /projects/{projectId}/analyses)
	QueueAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId)
	// DeleteAnalysis Delete an analysis
	// (DELETE /projects/{projectId}/analyses/{analysisId})
	DeleteAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId)
	// GetAnalysis Get an analysis' status and results
	// (GET /projects/{projectId}/analyses/{analysisId})
	GetAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId)
	// CancelAnalysis Cancel a running or queued analysis
	// (POST /projects/{projectId}/analyses/{analysisId}/cancel)
	CancelAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId)
	// QueueExport Queue an export with a version selection
	// (POST /projects/{projectId}/analyses/{analysisId}/exports)
	QueueExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId)
	// GetAnalysisLog Get an analysis' full log
	// (GET /projects/{projectId}/analyses/{analysisId}/log)
	GetAnalysisLog(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId)
	// DeleteExport Delete an export
	// (DELETE /projects/{projectId}/exports/{exportId})
	DeleteExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId)
	// GetExport Get an export's status and files
	// (GET /projects/{projectId}/exports/{exportId})
	GetExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId)
	// CancelExport Cancel a running or queued export
	// (POST /projects/{projectId}/exports/{exportId}/cancel)
	CancelExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId)
	// DownloadExportFile Download one file of a finished export
	// (GET /projects/{projectId}/exports/{exportId}/files/{name})
	DownloadExportFile(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId, name string)
	// SetProjectTarget Change the project's target platform and toolchain
	// (PUT /projects/{projectId}/target)
	SetProjectTarget(w http.ResponseWriter, r *http.Request, projectId ProjectId)
	// GetSettings Get settings, with signatureKey masked
	// (GET /settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// UpdateSettings Update settings
	// (PUT /settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// GetTools Installed and available tool versions, DB date
	// (GET /tools)
	GetTools(w http.ResponseWriter, r *http.Request)
	// ActivateTrivy Activate an installed Trivy version
	// (POST /tools/trivy/activate)
	ActivateTrivy(w http.ResponseWriter, r *http.Request)
	// UpdateTrivyDB Force a Trivy DB download
	// (POST /tools/trivy/db/update)
	UpdateTrivyDB(w http.ResponseWriter, r *http.Request)
	// UpdateTrivy Install a new Trivy release
	// (POST /tools/trivy/update)
	UpdateTrivy(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// WatchJob operation middleware
func (siw *ServerInterfaceWrapper) WatchJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.WatchJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsParams

	// ------------- Optional query parameter "manifestSha256" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "manifestSha256", r.URL.Query(), &params.ManifestSha256, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "manifestSha256"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "manifestSha256", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueAnalysis operation middleware
func (siw *ServerInterfaceWrapper) QueueAnalysis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueAnalysis(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAnalysis operation middleware
func (siw *ServerInterfaceWrapper) DeleteAnalysis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "analysisId" -------------
	var analysisId AnalysisId

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", r.PathValue("analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAnalysis(w, r, projectId, analysisId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalysis operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "analysisId" -------------
	var analysisId AnalysisId

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", r.PathValue("analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysis(w, r, projectId, analysisId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelAnalysis operation middleware
func (siw *ServerInterfaceWrapper) CancelAnalysis(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "analysisId" -------------
	var analysisId AnalysisId

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", r.PathValue("analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelAnalysis(w, r, projectId, analysisId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueueExport operation middleware
func (siw *ServerInterfaceWrapper) QueueExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "analysisId" -------------
	var analysisId AnalysisId

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", r.PathValue("analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueueExport(w, r, projectId, analysisId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAnalysisLog operation middleware
func (siw *ServerInterfaceWrapper) GetAnalysisLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "analysisId" -------------
	var analysisId AnalysisId

	err = runtime.BindStyledParameterWithOptions("simple", "analysisId", r.PathValue("analysisId"), &analysisId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "analysisId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAnalysisLog(w, r, projectId, analysisId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteExport operation middleware
func (siw *ServerInterfaceWrapper) DeleteExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "exportId" -------------
	var exportId ExportId

	err = runtime.BindStyledParameterWithOptions("simple", "exportId", r.PathValue("exportId"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exportId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteExport(w, r, projectId, exportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExport operation middleware
func (siw *ServerInterfaceWrapper) GetExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "exportId" -------------
	var exportId ExportId

	err = runtime.BindStyledParameterWithOptions("simple", "exportId", r.PathValue("exportId"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exportId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExport(w, r, projectId, exportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelExport operation middleware
func (siw *ServerInterfaceWrapper) CancelExport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "exportId" -------------
	var exportId ExportId

	err = runtime.BindStyledParameterWithOptions("simple", "exportId", r.PathValue("exportId"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exportId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelExport(w, r, projectId, exportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadExportFile operation middleware
func (siw *ServerInterfaceWrapper) DownloadExportFile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "exportId" -------------
	var exportId ExportId

	err = runtime.BindStyledParameterWithOptions("simple", "exportId", r.PathValue("exportId"), &exportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exportId", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadExportFile(w, r, projectId, exportId, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetProjectTarget operation middleware
func (siw *ServerInterfaceWrapper) SetProjectTarget(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "projectId" -------------
	var projectId ProjectId

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetProjectTarget(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTools operation middleware
func (siw *ServerInterfaceWrapper) GetTools(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTools(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ActivateTrivy operation middleware
func (siw *ServerInterfaceWrapper) ActivateTrivy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ActivateTrivy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrivyDB operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrivyDB(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrivyDB(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrivy operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrivy(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrivy(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/projects/{projectId}", wrapper.DeleteProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}", wrapper.GetProject)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{projectId}/target", wrapper.SetProjectTarget)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/analyses", wrapper.QueueAnalysis)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/projects/{projectId}/analyses/{analysisId}", wrapper.DeleteAnalysis)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/analyses/{analysisId}", wrapper.GetAnalysis)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/analyses/{analysisId}/log", wrapper.GetAnalysisLog)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/analyses/{analysisId}/cancel", wrapper.CancelAnalysis)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/analyses/{analysisId}/exports", wrapper.QueueExport)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/projects/{projectId}/exports/{exportId}", wrapper.DeleteExport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/exports/{exportId}", wrapper.GetExport)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{projectId}/exports/{exportId}/cancel", wrapper.CancelExport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{projectId}/exports/{exportId}/files/{name}", wrapper.DownloadExportFile)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/jobs/current/events", wrapper.WatchJob)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/settings", wrapper.GetSettings)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/settings", wrapper.UpdateSettings)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tools", wrapper.GetTools)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tools/trivy/update", wrapper.UpdateTrivy)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tools/trivy/activate", wrapper.ActivateTrivy)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tools/trivy/db/update", wrapper.UpdateTrivyDB)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type WatchJobRequestObject struct {
}

type WatchJobResponseObject interface {
	VisitWatchJobResponse(w http.ResponseWriter) error
}

type WatchJob200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response WatchJob200TexteventStreamResponse) VisitWatchJobResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type WatchJobdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response WatchJobdefaultApplicationProblemPlusJSONResponse) VisitWatchJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsRequestObject struct {
	Params ListProjectsParams
}

type ListProjectsResponseObject interface {
	VisitListProjectsResponse(w http.ResponseWriter) error
}

type ListProjects200JSONResponse []ProjectSummary

func (response ListProjects200JSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProjectsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListProjectsdefaultApplicationProblemPlusJSONResponse) VisitListProjectsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectRequestObject struct {
	Body *multipart.Reader
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateProjectdefaultApplicationProblemPlusJSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteProjectRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
}

type DeleteProjectResponseObject interface {
	VisitDeleteProjectResponse(w http.ResponseWriter) error
}

type DeleteProject204Response struct {
}

func (response DeleteProject204Response) VisitDeleteProjectResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProjectdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteProjectdefaultApplicationProblemPlusJSONResponse) VisitDeleteProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetProjectdefaultApplicationProblemPlusJSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type QueueAnalysisRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
}

type QueueAnalysisResponseObject interface {
	VisitQueueAnalysisResponse(w http.ResponseWriter) error
}

type QueueAnalysis202JSONResponse Analysis

func (response QueueAnalysis202JSONResponse) VisitQueueAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type QueueAnalysisdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response QueueAnalysisdefaultApplicationProblemPlusJSONResponse) VisitQueueAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteAnalysisRequestObject struct {
	ProjectId  ProjectId  `json:"projectId"`
	AnalysisId AnalysisId `json:"analysisId"`
}

type DeleteAnalysisResponseObject interface {
	VisitDeleteAnalysisResponse(w http.ResponseWriter) error
}

type DeleteAnalysis204Response struct {
}

func (response DeleteAnalysis204Response) VisitDeleteAnalysisResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteAnalysisdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteAnalysisdefaultApplicationProblemPlusJSONResponse) VisitDeleteAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAnalysisRequestObject struct {
	ProjectId  ProjectId  `json:"projectId"`
	AnalysisId AnalysisId `json:"analysisId"`
}

type GetAnalysisResponseObject interface {
	VisitGetAnalysisResponse(w http.ResponseWriter) error
}

type GetAnalysis200JSONResponse Analysis

func (response GetAnalysis200JSONResponse) VisitGetAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAnalysisdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAnalysisdefaultApplicationProblemPlusJSONResponse) VisitGetAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAnalysisRequestObject struct {
	ProjectId  ProjectId  `json:"projectId"`
	AnalysisId AnalysisId `json:"analysisId"`
}

type CancelAnalysisResponseObject interface {
	VisitCancelAnalysisResponse(w http.ResponseWriter) error
}

type CancelAnalysis200JSONResponse Analysis

func (response CancelAnalysis200JSONResponse) VisitCancelAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelAnalysisdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CancelAnalysisdefaultApplicationProblemPlusJSONResponse) VisitCancelAnalysisResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type QueueExportRequestObject struct {
	ProjectId  ProjectId  `json:"projectId"`
	AnalysisId AnalysisId `json:"analysisId"`
	Body       *QueueExportJSONRequestBody
}

type QueueExportResponseObject interface {
	VisitQueueExportResponse(w http.ResponseWriter) error
}

type QueueExport202JSONResponse Export

func (response QueueExport202JSONResponse) VisitQueueExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type QueueExportdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response QueueExportdefaultApplicationProblemPlusJSONResponse) VisitQueueExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetAnalysisLogRequestObject struct {
	ProjectId  ProjectId  `json:"projectId"`
	AnalysisId AnalysisId `json:"analysisId"`
}

type GetAnalysisLogResponseObject interface {
	VisitGetAnalysisLogResponse(w http.ResponseWriter) error
}

type GetAnalysisLog200TextResponse string

func (response GetAnalysisLog200TextResponse) VisitGetAnalysisLogResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetAnalysisLogdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetAnalysisLogdefaultApplicationProblemPlusJSONResponse) VisitGetAnalysisLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteExportRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
	ExportId  ExportId  `json:"exportId"`
}

type DeleteExportResponseObject interface {
	VisitDeleteExportResponse(w http.ResponseWriter) error
}

type DeleteExport204Response struct {
}

func (response DeleteExport204Response) VisitDeleteExportResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteExportdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DeleteExportdefaultApplicationProblemPlusJSONResponse) VisitDeleteExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetExportRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
	ExportId  ExportId  `json:"exportId"`
}

type GetExportResponseObject interface {
	VisitGetExportResponse(w http.ResponseWriter) error
}

type GetExport200JSONResponse Export

func (response GetExport200JSONResponse) VisitGetExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetExportdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetExportdefaultApplicationProblemPlusJSONResponse) VisitGetExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CancelExportRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
	ExportId  ExportId  `json:"exportId"`
}

type CancelExportResponseObject interface {
	VisitCancelExportResponse(w http.ResponseWriter) error
}

type CancelExport200JSONResponse Export

func (response CancelExport200JSONResponse) VisitCancelExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelExportdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CancelExportdefaultApplicationProblemPlusJSONResponse) VisitCancelExportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadExportFileRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
	ExportId  ExportId  `json:"exportId"`
	Name      string    `json:"name"`
}

type DownloadExportFileResponseObject interface {
	VisitDownloadExportFileResponse(w http.ResponseWriter) error
}

type DownloadExportFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response DownloadExportFile200ApplicationoctetStreamResponse) VisitDownloadExportFileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadExportFiledefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response DownloadExportFiledefaultApplicationProblemPlusJSONResponse) VisitDownloadExportFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SetProjectTargetRequestObject struct {
	ProjectId ProjectId `json:"projectId"`
	Body      *SetProjectTargetJSONRequestBody
}

type SetProjectTargetResponseObject interface {
	VisitSetProjectTargetResponse(w http.ResponseWriter) error
}

type SetProjectTarget200JSONResponse Project

func (response SetProjectTarget200JSONResponse) VisitSetProjectTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetProjectTargetdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SetProjectTargetdefaultApplicationProblemPlusJSONResponse) VisitSetProjectTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsRequestObject struct {
}

type GetSettingsResponseObject interface {
	VisitGetSettingsResponse(w http.ResponseWriter) error
}

type GetSettings200JSONResponse Settings

func (response GetSettings200JSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetSettingsdefaultApplicationProblemPlusJSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettingsRequestObject struct {
	Body *UpdateSettingsJSONRequestBody
}

type UpdateSettingsResponseObject interface {
	VisitUpdateSettingsResponse(w http.ResponseWriter) error
}

type UpdateSettings200JSONResponse Settings

func (response UpdateSettings200JSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettingsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateSettingsdefaultApplicationProblemPlusJSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolsRequestObject struct {
}

type GetToolsResponseObject interface {
	VisitGetToolsResponse(w http.ResponseWriter) error
}

type GetTools200JSONResponse ToolsState

func (response GetTools200JSONResponse) VisitGetToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetToolsdefaultApplicationProblemPlusJSONResponse) VisitGetToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateTrivyRequestObject struct {
	Body *ActivateTrivyJSONRequestBody
}

type ActivateTrivyResponseObject interface {
	VisitActivateTrivyResponse(w http.ResponseWriter) error
}

type ActivateTrivy200JSONResponse ToolsState

func (response ActivateTrivy200JSONResponse) VisitActivateTrivyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ActivateTrivydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ActivateTrivydefaultApplicationProblemPlusJSONResponse) VisitActivateTrivyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrivyDBRequestObject struct {
}

type UpdateTrivyDBResponseObject interface {
	VisitUpdateTrivyDBResponse(w http.ResponseWriter) error
}

type UpdateTrivyDB200JSONResponse ToolsState

func (response UpdateTrivyDB200JSONResponse) VisitUpdateTrivyDBResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrivyDBdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateTrivyDBdefaultApplicationProblemPlusJSONResponse) VisitUpdateTrivyDBResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrivyRequestObject struct {
	Body *UpdateTrivyJSONRequestBody
}

type UpdateTrivyResponseObject interface {
	VisitUpdateTrivyResponse(w http.ResponseWriter) error
}

type UpdateTrivy200JSONResponse ToolsState

func (response UpdateTrivy200JSONResponse) VisitUpdateTrivyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTrivydefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response UpdateTrivydefaultApplicationProblemPlusJSONResponse) VisitUpdateTrivyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// WatchJob Server-sent events of the running job
	// (GET /jobs/current/events)
	WatchJob(ctx context.Context, request WatchJobRequestObject) (WatchJobResponseObject, error)
	// ListProjects List projects with their last analysis and export
	// (GET /projects)
	ListProjects(ctx context.Context, request ListProjectsRequestObject) (ListProjectsResponseObject, error)
	// CreateProject Create a project from an uploaded package.json and start an analysis
	// (POST /projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// DeleteProject Delete the project directory
	// (DELETE /projects/{projectId})
	DeleteProject(ctx context.Context, request DeleteProjectRequestObject) (DeleteProjectResponseObject, error)
	// GetProject Get a project, its target and its history
	// (GET /projects/{projectId})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// QueueAnalysis Queue an analysis for the project
	// (POST /projects/{projectId}/analyses)
	QueueAnalysis(ctx context.Context, request QueueAnalysisRequestObject) (QueueAnalysisResponseObject, error)
	// DeleteAnalysis Delete an analysis
	// (DELETE /projects/{projectId}/analyses/{analysisId})
	DeleteAnalysis(ctx context.Context, request DeleteAnalysisRequestObject) (DeleteAnalysisResponseObject, error)
	// GetAnalysis Get an analysis' status and results
	// (GET /projects/{projectId}/analyses/{analysisId})
	GetAnalysis(ctx context.Context, request GetAnalysisRequestObject) (GetAnalysisResponseObject, error)
	// CancelAnalysis Cancel a running or queued analysis
	// (POST /projects/{projectId}/analyses/{analysisId}/cancel)
	CancelAnalysis(ctx context.Context, request CancelAnalysisRequestObject) (CancelAnalysisResponseObject, error)
	// QueueExport Queue an export with a version selection
	// (POST /projects/{projectId}/analyses/{analysisId}/exports)
	QueueExport(ctx context.Context, request QueueExportRequestObject) (QueueExportResponseObject, error)
	// GetAnalysisLog Get an analysis' full log
	// (GET /projects/{projectId}/analyses/{analysisId}/log)
	GetAnalysisLog(ctx context.Context, request GetAnalysisLogRequestObject) (GetAnalysisLogResponseObject, error)
	// DeleteExport Delete an export
	// (DELETE /projects/{projectId}/exports/{exportId})
	DeleteExport(ctx context.Context, request DeleteExportRequestObject) (DeleteExportResponseObject, error)
	// GetExport Get an export's status and files
	// (GET /projects/{projectId}/exports/{exportId})
	GetExport(ctx context.Context, request GetExportRequestObject) (GetExportResponseObject, error)
	// CancelExport Cancel a running or queued export
	// (POST /projects/{projectId}/exports/{exportId}/cancel)
	CancelExport(ctx context.Context, request CancelExportRequestObject) (CancelExportResponseObject, error)
	// DownloadExportFile Download one file of a finished export
	// (GET /projects/{projectId}/exports/{exportId}/files/{name})
	DownloadExportFile(ctx context.Context, request DownloadExportFileRequestObject) (DownloadExportFileResponseObject, error)
	// SetProjectTarget Change the project's target platform and toolchain
	// (PUT /projects/{projectId}/target)
	SetProjectTarget(ctx context.Context, request SetProjectTargetRequestObject) (SetProjectTargetResponseObject, error)
	// GetSettings Get settings, with signatureKey masked
	// (GET /settings)
	GetSettings(ctx context.Context, request GetSettingsRequestObject) (GetSettingsResponseObject, error)
	// UpdateSettings Update settings
	// (PUT /settings)
	UpdateSettings(ctx context.Context, request UpdateSettingsRequestObject) (UpdateSettingsResponseObject, error)
	// GetTools Installed and available tool versions, DB date
	// (GET /tools)
	GetTools(ctx context.Context, request GetToolsRequestObject) (GetToolsResponseObject, error)
	// ActivateTrivy Activate an installed Trivy version
	// (POST /tools/trivy/activate)
	ActivateTrivy(ctx context.Context, request ActivateTrivyRequestObject) (ActivateTrivyResponseObject, error)
	// UpdateTrivyDB Force a Trivy DB download
	// (POST /tools/trivy/db/update)
	UpdateTrivyDB(ctx context.Context, request UpdateTrivyDBRequestObject) (UpdateTrivyDBResponseObject, error)
	// UpdateTrivy Install a new Trivy release
	// (POST /tools/trivy/update)
	UpdateTrivy(ctx context.Context, request UpdateTrivyRequestObject) (UpdateTrivyResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// WatchJob operation middleware
func (sh *strictHandler) WatchJob(w http.ResponseWriter, r *http.Request) {
	var request WatchJobRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.WatchJob(ctx, request.(WatchJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "WatchJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WatchJobResponseObject); ok {
		if err := validResponse.VisitWatchJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProjects operation middleware
func (sh *strictHandler) ListProjects(w http.ResponseWriter, r *http.Request, params ListProjectsParams) {
	var request ListProjectsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProjects(ctx, request.(ListProjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProjects")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProjectsResponseObject); ok {
		if err := validResponse.VisitListProjectsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(w http.ResponseWriter, r *http.Request) {
	var request CreateProjectRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProject operation middleware
func (sh *strictHandler) DeleteProject(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	var request DeleteProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProject(ctx, request.(DeleteProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProjectResponseObject); ok {
		if err := validResponse.VisitDeleteProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	var request GetProjectRequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueueAnalysis operation middleware
func (sh *strictHandler) QueueAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	var request QueueAnalysisRequestObject

	request.ProjectId = projectId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueueAnalysis(ctx, request.(QueueAnalysisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueueAnalysis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueueAnalysisResponseObject); ok {
		if err := validResponse.VisitQueueAnalysisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAnalysis operation middleware
func (sh *strictHandler) DeleteAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId) {
	var request DeleteAnalysisRequestObject

	request.ProjectId = projectId
	request.AnalysisId = analysisId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAnalysis(ctx, request.(DeleteAnalysisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAnalysis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAnalysisResponseObject); ok {
		if err := validResponse.VisitDeleteAnalysisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAnalysis operation middleware
func (sh *strictHandler) GetAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId) {
	var request GetAnalysisRequestObject

	request.ProjectId = projectId
	request.AnalysisId = analysisId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnalysis(ctx, request.(GetAnalysisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnalysis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAnalysisResponseObject); ok {
		if err := validResponse.VisitGetAnalysisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelAnalysis operation middleware
func (sh *strictHandler) CancelAnalysis(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId) {
	var request CancelAnalysisRequestObject

	request.ProjectId = projectId
	request.AnalysisId = analysisId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelAnalysis(ctx, request.(CancelAnalysisRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelAnalysis")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelAnalysisResponseObject); ok {
		if err := validResponse.VisitCancelAnalysisResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueueExport operation middleware
func (sh *strictHandler) QueueExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId) {
	var request QueueExportRequestObject

	request.ProjectId = projectId
	request.AnalysisId = analysisId

	var body QueueExportJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueueExport(ctx, request.(QueueExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueueExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueueExportResponseObject); ok {
		if err := validResponse.VisitQueueExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAnalysisLog operation middleware
func (sh *strictHandler) GetAnalysisLog(w http.ResponseWriter, r *http.Request, projectId ProjectId, analysisId AnalysisId) {
	var request GetAnalysisLogRequestObject

	request.ProjectId = projectId
	request.AnalysisId = analysisId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAnalysisLog(ctx, request.(GetAnalysisLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAnalysisLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAnalysisLogResponseObject); ok {
		if err := validResponse.VisitGetAnalysisLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteExport operation middleware
func (sh *strictHandler) DeleteExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId) {
	var request DeleteExportRequestObject

	request.ProjectId = projectId
	request.ExportId = exportId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteExport(ctx, request.(DeleteExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteExportResponseObject); ok {
		if err := validResponse.VisitDeleteExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExport operation middleware
func (sh *strictHandler) GetExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId) {
	var request GetExportRequestObject

	request.ProjectId = projectId
	request.ExportId = exportId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExport(ctx, request.(GetExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExportResponseObject); ok {
		if err := validResponse.VisitGetExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelExport operation middleware
func (sh *strictHandler) CancelExport(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId) {
	var request CancelExportRequestObject

	request.ProjectId = projectId
	request.ExportId = exportId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelExport(ctx, request.(CancelExportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelExport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelExportResponseObject); ok {
		if err := validResponse.VisitCancelExportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadExportFile operation middleware
func (sh *strictHandler) DownloadExportFile(w http.ResponseWriter, r *http.Request, projectId ProjectId, exportId ExportId, name string) {
	var request DownloadExportFileRequestObject

	request.ProjectId = projectId
	request.ExportId = exportId
	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadExportFile(ctx, request.(DownloadExportFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadExportFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadExportFileResponseObject); ok {
		if err := validResponse.VisitDownloadExportFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetProjectTarget operation middleware
func (sh *strictHandler) SetProjectTarget(w http.ResponseWriter, r *http.Request, projectId ProjectId) {
	var request SetProjectTargetRequestObject

	request.ProjectId = projectId

	var body SetProjectTargetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetProjectTarget(ctx, request.(SetProjectTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetProjectTarget")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetProjectTargetResponseObject); ok {
		if err := validResponse.VisitSetProjectTargetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSettings operation middleware
func (sh *strictHandler) GetSettings(w http.ResponseWriter, r *http.Request) {
	var request GetSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettings(ctx, request.(GetSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSettingsResponseObject); ok {
		if err := validResponse.VisitGetSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSettings operation middleware
func (sh *strictHandler) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	var request UpdateSettingsRequestObject

	var body UpdateSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSettings(ctx, request.(UpdateSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateSettingsResponseObject); ok {
		if err := validResponse.VisitUpdateSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTools operation middleware
func (sh *strictHandler) GetTools(w http.ResponseWriter, r *http.Request) {
	var request GetToolsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTools(ctx, request.(GetToolsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTools")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetToolsResponseObject); ok {
		if err := validResponse.VisitGetToolsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ActivateTrivy operation middleware
func (sh *strictHandler) ActivateTrivy(w http.ResponseWriter, r *http.Request) {
	var request ActivateTrivyRequestObject

	var body ActivateTrivyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ActivateTrivy(ctx, request.(ActivateTrivyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ActivateTrivy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ActivateTrivyResponseObject); ok {
		if err := validResponse.VisitActivateTrivyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTrivyDB operation middleware
func (sh *strictHandler) UpdateTrivyDB(w http.ResponseWriter, r *http.Request) {
	var request UpdateTrivyDBRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTrivyDB(ctx, request.(UpdateTrivyDBRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTrivyDB")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTrivyDBResponseObject); ok {
		if err := validResponse.VisitUpdateTrivyDBResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTrivy operation middleware
func (sh *strictHandler) UpdateTrivy(w http.ResponseWriter, r *http.Request) {
	var request UpdateTrivyRequestObject

	var body UpdateTrivyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTrivy(ctx, request.(UpdateTrivyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTrivy")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTrivyResponseObject); ok {
		if err := validResponse.VisitUpdateTrivyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
