/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as SessionsSessionIdIndexRouteImport } from './routes/sessions.$sessionId.index'
import { Route as SessionsSessionIdAnalysisRouteImport } from './routes/sessions.$sessionId.analysis'
import { Route as SessionsSessionIdDropRouteImport } from './routes/sessions.$sessionId.drop'
import { Route as SessionsSessionIdReviewRouteImport } from './routes/sessions.$sessionId.review'
import { Route as ProjectsProjectIdAnalysesAnalysisIdExportRouteImport } from './routes/projects.$projectId_.analyses.$analysisId.export'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdIndexRoute = SessionsSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const SessionsSessionIdAnalysisRoute =
  SessionsSessionIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)
const SessionsSessionIdDropRoute = SessionsSessionIdDropRouteImport.update({
  id: '/drop',
  path: '/drop',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const SessionsSessionIdReviewRoute = SessionsSessionIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)
const ProjectsProjectIdAnalysesAnalysisIdExportRoute =
  ProjectsProjectIdAnalysesAnalysisIdExportRouteImport.update({
    id: '/projects/$projectId_/analyses/$analysisId/export',
    path: '/projects/$projectId/analyses/$analysisId/export',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/analysis': typeof SessionsSessionIdAnalysisRoute
  '/sessions/$sessionId/drop': typeof SessionsSessionIdDropRoute
  '/sessions/$sessionId/review': typeof SessionsSessionIdReviewRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/projects/$projectId/analyses/$analysisId/export': typeof ProjectsProjectIdAnalysesAnalysisIdExportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sessions/$sessionId/analysis': typeof SessionsSessionIdAnalysisRoute
  '/sessions/$sessionId/drop': typeof SessionsSessionIdDropRoute
  '/sessions/$sessionId/review': typeof SessionsSessionIdReviewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdIndexRoute
  '/projects/$projectId/analyses/$analysisId/export': typeof ProjectsProjectIdAnalysesAnalysisIdExportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/analysis': typeof SessionsSessionIdAnalysisRoute
  '/sessions/$sessionId/drop': typeof SessionsSessionIdDropRoute
  '/sessions/$sessionId/review': typeof SessionsSessionIdReviewRoute
  '/sessions/$sessionId/': typeof SessionsSessionIdIndexRoute
  '/projects/$projectId_/analyses/$analysisId/export': typeof ProjectsProjectIdAnalysesAnalysisIdExportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/analysis'
    | '/sessions/$sessionId/drop'
    | '/sessions/$sessionId/review'
    | '/sessions/$sessionId/'
    | '/projects/$projectId/analyses/$analysisId/export'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sessions/$sessionId/analysis'
    | '/sessions/$sessionId/drop'
    | '/sessions/$sessionId/review'
    | '/sessions/$sessionId'
    | '/projects/$projectId/analyses/$analysisId/export'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/analysis'
    | '/sessions/$sessionId/drop'
    | '/sessions/$sessionId/review'
    | '/sessions/$sessionId/'
    | '/projects/$projectId_/analyses/$analysisId/export'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  ProjectsProjectIdAnalysesAnalysisIdExportRoute: typeof ProjectsProjectIdAnalysesAnalysisIdExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/': {
      id: '/sessions/$sessionId/'
      path: '/'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof SessionsSessionIdIndexRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/analysis': {
      id: '/sessions/$sessionId/analysis'
      path: '/analysis'
      fullPath: '/sessions/$sessionId/analysis'
      preLoaderRoute: typeof SessionsSessionIdAnalysisRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/drop': {
      id: '/sessions/$sessionId/drop'
      path: '/drop'
      fullPath: '/sessions/$sessionId/drop'
      preLoaderRoute: typeof SessionsSessionIdDropRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/sessions/$sessionId/review': {
      id: '/sessions/$sessionId/review'
      path: '/review'
      fullPath: '/sessions/$sessionId/review'
      preLoaderRoute: typeof SessionsSessionIdReviewRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/projects/$projectId_/analyses/$analysisId/export': {
      id: '/projects/$projectId_/analyses/$analysisId/export'
      path: '/projects/$projectId/analyses/$analysisId/export'
      fullPath: '/projects/$projectId/analyses/$analysisId/export'
      preLoaderRoute: typeof ProjectsProjectIdAnalysesAnalysisIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdAnalysisRoute: typeof SessionsSessionIdAnalysisRoute
  SessionsSessionIdDropRoute: typeof SessionsSessionIdDropRoute
  SessionsSessionIdReviewRoute: typeof SessionsSessionIdReviewRoute
  SessionsSessionIdIndexRoute: typeof SessionsSessionIdIndexRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdAnalysisRoute: SessionsSessionIdAnalysisRoute,
  SessionsSessionIdDropRoute: SessionsSessionIdDropRoute,
  SessionsSessionIdReviewRoute: SessionsSessionIdReviewRoute,
  SessionsSessionIdIndexRoute: SessionsSessionIdIndexRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  ProjectsProjectIdAnalysesAnalysisIdExportRoute:
    ProjectsProjectIdAnalysesAnalysisIdExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
